openshift.withCluster() { 
    def created = openshift.newApp( 'gimboo/nginx_nonroot' )        
    echo "new-app created ${created.count()} objects named: ${created.names()}"
    
    //zawezenie selectora do servicu
    def services = created.narrow('services')
 stage('build')
    //zawezenie selectora do dc
    def dcs = created.narrow('dc')
    def dc = dcs.object()
    echo "new-app created a ${dc.kind} with name ${dc.metadata.name}"
    echo "The object has labels: ${dc.metadata.labels}"
        
}
